#!/bin/bash
#

list=`ls tests/test.??`

tmpfile=test$$.tmp
failed="0"

for file in $list
do
  test=`echo $file | cut -f2 -d\.`
  echo "Running test $test..."
  source $file 2>/dev/null >$tmpfile
  exitcode=$?

  if [ -f ${file}.out ]
  then
    if ! diff $tmpfile ${file}.out
    then
      failed=$[ $failed + 1 ]
    fi
  else
    echo "...new test, copying out file"
    cp $tmpfile ${file}.out
  fi
  rm $tmpfile
  echo "$exitcode" >$tmpfile
  if [ -f ${file}.ec ]
  then
    if ! diff $tmpfile ${file}.ec
    then
      failed=$[ $failed + 1 ]
    fi
  else
    echo "...new test, copying ec file"
    cp $tmpfile ${file}.ec
  fi
  rm $tmpfile
done

if [ "$failed" -gt "0" ]
then
  echo $failed tests failed
  exit 1
fi

exit 0
